/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../src/chips/chips.module';
import * as i2 from '@angular/common';
import * as i3 from '@angular/forms';
import * as i4 from 'ngx-chips/dist/modules/core/providers/drag-provider';
import * as i5 from 'ng2-material-dropdown/dist/src/modules/ng2-dropdown.module';
import * as i6 from 'ngx-chips/dist/modules/tag-input.module';
export const FormlyChipsModuleNgFactory:i0.NgModuleFactory<i1.FormlyChipsModule> = i0.ɵcmf(i1.FormlyChipsModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,
          i2.NgLocalization,i2.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(4608,i3.ɵi,
          i3.ɵi,([] as any[])),i0.ɵmpd(4608,i3.FormBuilder,i3.FormBuilder,([] as any[])),
          i0.ɵmpd(4608,i4.DragProvider,i4.DragProvider,([] as any[])),i0.ɵmpd(512,
              i2.CommonModule,i2.CommonModule,([] as any[])),i0.ɵmpd(512,i3.ɵba,i3.ɵba,
              ([] as any[])),i0.ɵmpd(512,i3.FormsModule,i3.FormsModule,([] as any[])),
          i0.ɵmpd(512,i3.ReactiveFormsModule,i3.ReactiveFormsModule,([] as any[])),
          i0.ɵmpd(512,i5.Ng2DropdownModule,i5.Ng2DropdownModule,([] as any[])),i0.ɵmpd(512,
              i6.TagInputModule,i6.TagInputModule,([] as any[])),i0.ɵmpd(512,i1.FormlyChipsModule,
              i1.FormlyChipsModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRTovRE9XTkxPQURTIDIwMTAvU29mbGV4L05QTS9uZ3gtZm9ybWx5LWNvbXBvbmVudHMvc3JjL2NoaXBzL2NoaXBzLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9FOi9ET1dOTE9BRFMgMjAxMC9Tb2ZsZXgvTlBNL25neC1mb3JtbHktY29tcG9uZW50cy9zcmMvY2hpcHMvY2hpcHMubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
