/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../src/formly-components.module';
import * as i2 from '../node_modules/ng-formly/lib/src/core/components/formly.group.ngfactory';
import * as i3 from '../node_modules/ng-formly/lib/src/ui-bootstrap/types/input.ngfactory';
import * as i4 from '../node_modules/ng-formly/lib/src/ui-bootstrap/types/checkbox.ngfactory';
import * as i5 from '../node_modules/ng-formly/lib/src/ui-bootstrap/types/radio.ngfactory';
import * as i6 from '../node_modules/ng-formly/lib/src/ui-bootstrap/types/select.ngfactory';
import * as i7 from '../node_modules/ng-formly/lib/src/ui-bootstrap/types/textarea.ngfactory';
import * as i8 from '../node_modules/ng-formly/lib/src/ui-bootstrap/types/multicheckbox.ngfactory';
import * as i9 from '../node_modules/ng-formly/lib/src/ui-bootstrap/wrappers/label.ngfactory';
import * as i10 from '../node_modules/ng-formly/lib/src/ui-bootstrap/wrappers/description.ngfactory';
import * as i11 from '../node_modules/ng-formly/lib/src/ui-bootstrap/wrappers/message-validation.ngfactory';
import * as i12 from '../node_modules/ng-formly/lib/src/ui-bootstrap/wrappers/fieldset.ngfactory';
import * as i13 from '../node_modules/ng-formly/lib/src/ui-bootstrap/wrappers/addons.ngfactory';
import * as i14 from './datetime-mask/datetime-mask.component.ngfactory';
import * as i15 from './select-async/select-async.component.ngfactory';
import * as i16 from './chips/chips.component.ngfactory';
import * as i17 from '@angular/common';
import * as i18 from '@angular/forms';
import * as i19 from 'ng-formly/lib/src/core/services/formly.config';
import * as i20 from 'ng-formly/lib/src/core/services/formly.form.builder';
import * as i21 from 'ng-formly/lib/src/core/services/formly.event.emitter';
import * as i22 from 'ng-formly/lib/src/core/services/formly.validation-messages';
import * as i23 from 'ngx-chips/dist/modules/core/providers/drag-provider';
import * as i24 from 'ng-formly/lib/src/core/core.module';
import * as i25 from 'ng-formly/lib/src/ui-bootstrap/ui-bootstrap.module';
import * as i26 from 'angular2-text-mask/dist/angular2TextMask';
import * as i27 from '../../src/datetime-mask/datetime-mask.module';
import * as i28 from 'ng2-select/select/select.module';
import * as i29 from '../../src/select-async/select-async.module';
import * as i30 from 'ng2-material-dropdown/dist/src/modules/ng2-dropdown.module';
import * as i31 from 'ngx-chips/dist/modules/tag-input.module';
import * as i32 from '../../src/chips/chips.module';
import * as i33 from 'ng-formly/lib/src/ui-bootstrap/types/input';
import * as i34 from 'ng-formly/lib/src/ui-bootstrap/types/checkbox';
import * as i35 from 'ng-formly/lib/src/ui-bootstrap/types/radio';
import * as i36 from 'ng-formly/lib/src/ui-bootstrap/types/select';
import * as i37 from 'ng-formly/lib/src/ui-bootstrap/types/textarea';
import * as i38 from 'ng-formly/lib/src/ui-bootstrap/types/multicheckbox';
import * as i39 from 'ng-formly/lib/src/ui-bootstrap/wrappers/label';
import * as i40 from 'ng-formly/lib/src/ui-bootstrap/wrappers/description';
import * as i41 from 'ng-formly/lib/src/ui-bootstrap/wrappers/message-validation';
import * as i42 from 'ng-formly/lib/src/ui-bootstrap/wrappers/fieldset';
import * as i43 from 'ng-formly/lib/src/ui-bootstrap/wrappers/addons';
import * as i44 from 'ng-formly/lib/src/ui-bootstrap/run/description';
import * as i45 from 'ng-formly/lib/src/ui-bootstrap/run/validation';
import * as i46 from 'ng-formly/lib/src/ui-bootstrap/run/addon';
import * as i47 from '../../src/datetime-mask/datetime-mask.component';
import * as i48 from '../../src/select-async/select-async.component';
import * as i49 from '../../src/chips/chips.component';
export const FormlyComponentsRootModuleNgFactory:i0.NgModuleFactory<i1.FormlyComponentsRootModule> = i0.ɵcmf(i1.FormlyComponentsRootModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.FormlyGroupNgFactory,i3.FormlyFieldInputNgFactory,i4.FormlyFieldCheckboxNgFactory,
              i5.FormlyFieldRadioNgFactory,i6.FormlyFieldSelectNgFactory,i7.FormlyFieldTextAreaNgFactory,
              i8.FormlyFieldMultiCheckboxNgFactory,i9.FormlyWrapperLabelNgFactory,
              i10.FormlyWrapperDescriptionNgFactory,i11.FormlyWrapperValidationMessagesNgFactory,
              i12.FormlyWrapperFieldsetNgFactory,i13.FormlyWrapperAddonsNgFactory,
              i14.FormlyDateTimeMaskComponentNgFactory,i15.FormlySelectAsyncComponentNgFactory,
              i16.FormlyChipsComponentNgFactory]],[3,i0.ComponentFactoryResolver],
              i0.NgModuleRef]),i0.ɵmpd(4608,i17.NgLocalization,i17.NgLocaleLocalization,
          [i0.LOCALE_ID]),i0.ɵmpd(4608,i18.ɵi,i18.ɵi,([] as any[])),i0.ɵmpd(4608,i18.FormBuilder,
          i18.FormBuilder,([] as any[])),i0.ɵmpd(4608,i19.FormlyConfig,i19.FormlyConfig,
          [i19.FORMLY_CONFIG_TOKEN]),i0.ɵmpd(4608,i20.FormlyFormBuilder,i20.FormlyFormBuilder,
          [i19.FormlyConfig]),i0.ɵmpd(4608,i21.FormlyPubSub,i21.FormlyPubSub,([] as any[])),
          i0.ɵmpd(4608,i22.FormlyValidationMessages,i22.FormlyValidationMessages,[i19.FORMLY_CONFIG_TOKEN]),
          i0.ɵmpd(4608,i23.DragProvider,i23.DragProvider,([] as any[])),i0.ɵmpd(512,
              i17.CommonModule,i17.CommonModule,([] as any[])),i0.ɵmpd(512,i18.ɵba,
              i18.ɵba,([] as any[])),i0.ɵmpd(512,i18.FormsModule,i18.FormsModule,([] as any[])),
          i0.ɵmpd(512,i18.ReactiveFormsModule,i18.ReactiveFormsModule,([] as any[])),
          i0.ɵmpd(512,i24.FormlyModule,i24.FormlyModule,([] as any[])),i0.ɵmpd(512,
              i25.FormlyBootstrapModule,i25.FormlyBootstrapModule,([] as any[])),i0.ɵmpd(512,
              i26.TextMaskModule,i26.TextMaskModule,([] as any[])),i0.ɵmpd(512,i27.FormlyDatetimeMaskModule,
              i27.FormlyDatetimeMaskModule,([] as any[])),i0.ɵmpd(512,i28.SelectModule,
              i28.SelectModule,([] as any[])),i0.ɵmpd(512,i29.FormlySelectAsyncModule,
              i29.FormlySelectAsyncModule,([] as any[])),i0.ɵmpd(512,i30.Ng2DropdownModule,
              i30.Ng2DropdownModule,([] as any[])),i0.ɵmpd(512,i31.TagInputModule,
              i31.TagInputModule,([] as any[])),i0.ɵmpd(512,i32.FormlyChipsModule,
              i32.FormlyChipsModule,([] as any[])),i0.ɵmpd(512,i1.FormlyComponentsRootModule,
              i1.FormlyComponentsRootModule,([] as any[])),i0.ɵmpd(1024,i19.FORMLY_CONFIG_TOKEN,
              () => {
                return [{types:[{name:'input',component:i33.FormlyFieldInput,wrappers:['fieldset',
                    'label']},{name:'checkbox',component:i34.FormlyFieldCheckbox,wrappers:['fieldset']},
                    {name:'radio',component:i35.FormlyFieldRadio,wrappers:['fieldset',
                        'label']},{name:'select',component:i36.FormlyFieldSelect,wrappers:['fieldset',
                        'label']},{name:'textarea',component:i37.FormlyFieldTextArea,
                        wrappers:['fieldset','label']},{name:'multicheckbox',component:i38.FormlyFieldMultiCheckbox,
                        wrappers:['fieldset','label']}],wrappers:[{name:'label',component:i39.FormlyWrapperLabel},
                    {name:'description',component:i40.FormlyWrapperDescription},{name:'validation-message',
                        component:i41.FormlyWrapperValidationMessages},{name:'fieldset',
                        component:i42.FormlyWrapperFieldset},{name:'addons',component:i43.FormlyWrapperAddons}],
                    manipulators:[{class:i44.TemplateDescription,method:'run'},{class:i45.TemplateValidation,
                        method:'run'},{class:i46.TemplateAddons,method:'run'}]},{types:[{name:'datetime-mask',
                    component:i47.FormlyDateTimeMaskComponent},{name:'select-async',
                    component:i48.FormlySelectAsyncComponent},{name:'chips',component:i49.FormlyChipsComponent}]}];
              },([] as any[]))]);
    });
export const FormlyComponentsModuleNgFactory:i0.NgModuleFactory<i1.FormlyComponentsModule> = i0.ɵcmf(i1.FormlyComponentsModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.FormlyGroupNgFactory,i3.FormlyFieldInputNgFactory,i4.FormlyFieldCheckboxNgFactory,
              i5.FormlyFieldRadioNgFactory,i6.FormlyFieldSelectNgFactory,i7.FormlyFieldTextAreaNgFactory,
              i8.FormlyFieldMultiCheckboxNgFactory,i9.FormlyWrapperLabelNgFactory,
              i10.FormlyWrapperDescriptionNgFactory,i11.FormlyWrapperValidationMessagesNgFactory,
              i12.FormlyWrapperFieldsetNgFactory,i13.FormlyWrapperAddonsNgFactory,
              i14.FormlyDateTimeMaskComponentNgFactory,i15.FormlySelectAsyncComponentNgFactory]],
              [3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,i17.NgLocalization,
          i17.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(4608,i18.FormBuilder,i18.FormBuilder,
          ([] as any[])),i0.ɵmpd(4608,i18.ɵi,i18.ɵi,([] as any[])),i0.ɵmpd(4608,i19.FormlyConfig,
          i19.FormlyConfig,[i19.FORMLY_CONFIG_TOKEN]),i0.ɵmpd(4608,i20.FormlyFormBuilder,
          i20.FormlyFormBuilder,[i19.FormlyConfig]),i0.ɵmpd(4608,i21.FormlyPubSub,
          i21.FormlyPubSub,([] as any[])),i0.ɵmpd(4608,i22.FormlyValidationMessages,
          i22.FormlyValidationMessages,[i19.FORMLY_CONFIG_TOKEN]),i0.ɵmpd(4608,i23.DragProvider,
          i23.DragProvider,([] as any[])),i0.ɵmpd(512,i17.CommonModule,i17.CommonModule,
          ([] as any[])),i0.ɵmpd(512,i18.ɵba,i18.ɵba,([] as any[])),i0.ɵmpd(512,i18.ReactiveFormsModule,
          i18.ReactiveFormsModule,([] as any[])),i0.ɵmpd(512,i24.FormlyModule,i24.FormlyModule,
          ([] as any[])),i0.ɵmpd(512,i25.FormlyBootstrapModule,i25.FormlyBootstrapModule,
          ([] as any[])),i0.ɵmpd(512,i18.FormsModule,i18.FormsModule,([] as any[])),
          i0.ɵmpd(512,i26.TextMaskModule,i26.TextMaskModule,([] as any[])),i0.ɵmpd(512,
              i27.FormlyDatetimeMaskModule,i27.FormlyDatetimeMaskModule,([] as any[])),
          i0.ɵmpd(512,i28.SelectModule,i28.SelectModule,([] as any[])),i0.ɵmpd(512,
              i29.FormlySelectAsyncModule,i29.FormlySelectAsyncModule,([] as any[])),
          i0.ɵmpd(512,i30.Ng2DropdownModule,i30.Ng2DropdownModule,([] as any[])),i0.ɵmpd(512,
              i31.TagInputModule,i31.TagInputModule,([] as any[])),i0.ɵmpd(512,i32.FormlyChipsModule,
              i32.FormlyChipsModule,([] as any[])),i0.ɵmpd(512,i1.FormlyComponentsModule,
              i1.FormlyComponentsModule,([] as any[])),i0.ɵmpd(1024,i19.FORMLY_CONFIG_TOKEN,
              () => {
                return [{types:[{name:'input',component:i33.FormlyFieldInput,wrappers:['fieldset',
                    'label']},{name:'checkbox',component:i34.FormlyFieldCheckbox,wrappers:['fieldset']},
                    {name:'radio',component:i35.FormlyFieldRadio,wrappers:['fieldset',
                        'label']},{name:'select',component:i36.FormlyFieldSelect,wrappers:['fieldset',
                        'label']},{name:'textarea',component:i37.FormlyFieldTextArea,
                        wrappers:['fieldset','label']},{name:'multicheckbox',component:i38.FormlyFieldMultiCheckbox,
                        wrappers:['fieldset','label']}],wrappers:[{name:'label',component:i39.FormlyWrapperLabel},
                    {name:'description',component:i40.FormlyWrapperDescription},{name:'validation-message',
                        component:i41.FormlyWrapperValidationMessages},{name:'fieldset',
                        component:i42.FormlyWrapperFieldset},{name:'addons',component:i43.FormlyWrapperAddons}],
                    manipulators:[{class:i44.TemplateDescription,method:'run'},{class:i45.TemplateValidation,
                        method:'run'},{class:i46.TemplateAddons,method:'run'}]}];
              },([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRTovRE9XTkxPQURTIDIwMTAvU29mbGV4L05QTS9uZ3gtZm9ybWx5LWNvbXBvbmVudHMvc3JjL2Zvcm1seS1jb21wb25lbnRzLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9FOi9ET1dOTE9BRFMgMjAxMC9Tb2ZsZXgvTlBNL25neC1mb3JtbHktY29tcG9uZW50cy9zcmMvZm9ybWx5LWNvbXBvbmVudHMubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
