/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../src/datetime-mask/datetime-mask.module';
import * as i2 from './datetime-mask.component.ngfactory';
import * as i3 from '@angular/common';
import * as i4 from '@angular/forms';
import * as i5 from 'angular2-text-mask/dist/angular2TextMask';
export const FormlyDatetimeMaskModuleNgFactory:i0.NgModuleFactory<i1.FormlyDatetimeMaskModule> = i0.ɵcmf(i1.FormlyDatetimeMaskModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.FormlyDateTimeMaskComponentNgFactory]],[3,i0.ComponentFactoryResolver],
              i0.NgModuleRef]),i0.ɵmpd(4608,i3.NgLocalization,i3.NgLocaleLocalization,
          [i0.LOCALE_ID]),i0.ɵmpd(4608,i4.ɵi,i4.ɵi,([] as any[])),i0.ɵmpd(4608,i4.FormBuilder,
          i4.FormBuilder,([] as any[])),i0.ɵmpd(512,i3.CommonModule,i3.CommonModule,
          ([] as any[])),i0.ɵmpd(512,i4.ɵba,i4.ɵba,([] as any[])),i0.ɵmpd(512,i4.FormsModule,
          i4.FormsModule,([] as any[])),i0.ɵmpd(512,i4.ReactiveFormsModule,i4.ReactiveFormsModule,
          ([] as any[])),i0.ɵmpd(512,i5.TextMaskModule,i5.TextMaskModule,([] as any[])),
          i0.ɵmpd(512,i1.FormlyDatetimeMaskModule,i1.FormlyDatetimeMaskModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRTovRE9XTkxPQURTIDIwMTAvU29mbGV4L05QTS9uZ3gtZm9ybWx5LWNvbXBvbmVudHMvc3JjL2RhdGV0aW1lLW1hc2svZGF0ZXRpbWUtbWFzay5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRTovRE9XTkxPQURTIDIwMTAvU29mbGV4L05QTS9uZ3gtZm9ybWx5LWNvbXBvbmVudHMvc3JjL2RhdGV0aW1lLW1hc2svZGF0ZXRpbWUtbWFzay5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
