/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../src/select-async/select-async.module';
import * as i2 from './select-async.component.ngfactory';
import * as i3 from '@angular/common';
import * as i4 from '@angular/forms';
import * as i5 from 'ng2-select/select/select.module';
export const FormlySelectAsyncModuleNgFactory:i0.NgModuleFactory<i1.FormlySelectAsyncModule> = i0.ɵcmf(i1.FormlySelectAsyncModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.FormlySelectAsyncComponentNgFactory]],[3,i0.ComponentFactoryResolver],
              i0.NgModuleRef]),i0.ɵmpd(4608,i3.NgLocalization,i3.NgLocaleLocalization,
          [i0.LOCALE_ID]),i0.ɵmpd(4608,i4.ɵi,i4.ɵi,([] as any[])),i0.ɵmpd(4608,i4.FormBuilder,
          i4.FormBuilder,([] as any[])),i0.ɵmpd(512,i3.CommonModule,i3.CommonModule,
          ([] as any[])),i0.ɵmpd(512,i4.ɵba,i4.ɵba,([] as any[])),i0.ɵmpd(512,i4.FormsModule,
          i4.FormsModule,([] as any[])),i0.ɵmpd(512,i4.ReactiveFormsModule,i4.ReactiveFormsModule,
          ([] as any[])),i0.ɵmpd(512,i5.SelectModule,i5.SelectModule,([] as any[])),
          i0.ɵmpd(512,i1.FormlySelectAsyncModule,i1.FormlySelectAsyncModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRTovRE9XTkxPQURTIDIwMTAvU29mbGV4L05QTS9uZ3gtZm9ybWx5LWNvbXBvbmVudHMvc3JjL3NlbGVjdC1hc3luYy9zZWxlY3QtYXN5bmMubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0U6L0RPV05MT0FEUyAyMDEwL1NvZmxleC9OUE0vbmd4LWZvcm1seS1jb21wb25lbnRzL3NyYy9zZWxlY3QtYXN5bmMvc2VsZWN0LWFzeW5jLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
